name: "Linter for Markdown"

on:
  push:
    branches: [main]
    paths:
      - 'docs-rtd/**'
  pull_request:
    paths:
      - 'docs-rtd/**'
  workflow_dispatch:
    paths:
      - 'docs-rtd/**'

jobs:
  markdown-lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          config: "docs-rtd/.sphinx/.markdownlint.json"
          globs: "docs-rtd/**/*.md"
          continue-on-error: true
